######################################
#### manual configuration example: ###
#Twitter:
#  access_token: XXX-XXX
#  access_token_secret: XXX
#  consumer_key: XXX
#  consumer_secret: XXX
#
#Discord:
#  - IncludeReplyToUser: false
#    IncludeRetweet: false
#    IncludeUserReply: true
#    custom_message: 'A new tweet!'
#    keyword_sets:
#    - - 'League'    # tweet will be posted if tweet contains all 3 words {League of Legends}, no particular order.
#      - 'of'
#      - 'Legends'
#    - - 'Dota 2'    # tweet will be posted if tweet contains 'Dota 2' in this specific order
#    - - 'MOBA'      # tweet will be posted if it contains 'MOBA'
#    twitter_ids:
#    - '123'         # define as many as you want with a dash {-} at the beginning
#    - '456'
#    twitter_handles:
#    - 'discordapp'
#    twitter_lists:
#    - 'https://twitter.com/rokxx/lists/dota-2'
#    webhook_urls:
#    - 'https://discordapp.com/api/webhooks/123456/XXXX-XXXX'
######################################

# configuration through environment variables
Twitter:
  access_token: ${ACCESS_TOKEN}
  access_token_secret: ${ACCESS_TOKEN_SECRET}
  consumer_key: ${CONSUMER_KEY}
  consumer_secret: ${CONSUMER_SECRET}

# configuration through environment variables
Discord:
# configuration here in config.yml
# test
  - CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: 
    blackword_sets: 
    twitter_ids: 
    webhook_urls: 
#1    
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: 
    blackword_sets: [['法的措置']]
    twitter_ids: ['317684165','3225848184','712096712148459520','804291413831610368','847023967458111490','918648028432498693','929625878249684992','1050154318505029632','1105642239340900352','1241757146473095168','1305347370599641088','1322080600006684672','1314640424062001152','1114009227402416128','1327162323291631616','914715968995291136','1333371891453546497','1345751760682381312','3225848184','841969300164362240','1363669961080643588','1369011665824411652','1386489808118185985','1206451556675010560','1260730524328321025','1253595964444520448','1410856278474117122','1410507389497856008','1412011482724769796']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#2
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: true
    IncludeAttachment: true
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: 
    blackword_sets: 
    twitter_ids: ['1001065920234573824','846729851427971073']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#3
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: 
    blackword_sets: [['誰かに話したくなる東京ディズニーリゾート']]
    twitter_ids: ['2569334192','1307929737042427904','1193156715836887041','1219889357810585600','1288392968433356800','1297996538375892994','1309354515724812288','4077236000']
    webhook_urls: ['https://discord.com/api/webhooks/822748579508649994/OeAwr_TCBvcEhsKshAFrjJjHR7GHHGzAUZd4u5J71thOyzlYKNzKpxKQ6kZDlZe7XFWF']
#4
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['乃木坂','t.co'],['みなみ','t.co'],['桃','t.co'],['サンデー','t.co'],['ちゃん','t.co'],['t.co']]
    blackword_sets: [['浜中文一'],['TravisJapan'],['サタデー'],['中村海人'],['HeySayJUMP'],['八乙女光'],['伊野尾慧'],['Lilかんさい'],['SexyZone'],['SixTONES'],['嶋﨑斗亜'],['ジェシー'],['髙地優吾'],['くん'],['radirer'],['nhk.or.jp/radirer'],['nhk.or.jp/radirer/sunday/basic_sun'],['してみよう'],['なんて言った'],['なんていった'],['投稿してね'],['送ってね'],['考えてね'],['企画です'],['【サンデー】①'],['【サンデー】②']]
    twitter_ids: ['505321772']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#5
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['乃木坂','t.co'],['田村真佑','t.co']]
    blackword_sets: [['郡司芹香']]
    twitter_ids: ['1511776262,2212674829','1014831411935625216']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#6
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['乃木坂','t.co'],['乃木坂','アメブロ'],['斉藤優里','t.co'],['斉藤優里','アメブロ'],['月曜','t.co'],['月曜','アメブロ'],['擬音クエスト','t.co'],['擬音クエスト','アメブロ'],['ドンバト','月曜テーマ'],['(月)','t.co'],['(月)','アメブロ'],['明日のドンバトテーマ','t.co'],['明日のドンバトテーマ','アメブロ']]
    blackword_sets: [['来週月曜日']]
    twitter_ids: ['388341040']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#7
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['showroom']]
    blackword_sets: 
    twitter_ids: ['317684165']
    webhook_urls: ['https://discord.com/api/webhooks/822748986699939851/FfcBtI7Ow-iUFfi2pcz7XpGXGni3ZH0geUgXpsnzTaYXeFPevdj76THQWL9P95J9cJPr','https://discord.com/api/webhooks/822749298278137898/gK_hN_pB3zZHOgVbJHrtp2dxREZV_SpcSrxhqHNSIlU-2zM36BaHURg0016uZ_REIGZT']
#8
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['齋藤飛鳥','t.co'],['沈黙の金曜日','t.co']]
    blackword_sets: 
    twitter_ids: ['714315534632792064','3096208460']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#9
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['乃木坂46'],['堀未央奈'],['与田祐希'],['トップ目とれるカナ','t.co']]
    blackword_sets: 
    twitter_ids: ['226517544','4066572320','837626591245037568','873066157086957568','772685974358724608','1215185992153387008','130040008']
    webhook_urls: ['https://discord.com/api/webhooks/822596008394752061/fuscve015WABiqds3j-JfmH32pCiIqC5X90yU0tLiMd2RFreKLdAPhW1vgOvu1eqzYWl']
#10
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['asdf']]
    blackword_sets: [['zxcv']]
    twitter_ids: ['3064628602']
    webhook_urls: ['https://discord.com/api/webhooks/822749512443494410/uH8dqAVhpLHQKFqzR_VBGbRJxrG6Wqd9ApOTYzCse43vg6MONeEoO18h9H9E6BwLD9ih']
#11
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['t.co']]
    blackword_sets: 
    twitter_ids: ['952446912069648385']
    webhook_urls: ['https://discord.com/api/webhooks/822748986699939851/FfcBtI7Ow-iUFfi2pcz7XpGXGni3ZH0geUgXpsnzTaYXeFPevdj76THQWL9P95J9cJPr']
#12
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['乃木坂46完売表']]
    blackword_sets: 
    twitter_ids: ['62048976']
    webhook_urls: ['https://discord.com/api/webhooks/822748986699939851/FfcBtI7Ow-iUFfi2pcz7XpGXGni3ZH0geUgXpsnzTaYXeFPevdj76THQWL9P95J9cJPr','https://discord.com/api/webhooks/855519066097057792/q4-euqyFJBIaLkksncJ82lTrYrfyNa2KsYgeJ0RrU7_p8OOE8g8NlcV9NN9jneen1LWP']
#13
  - IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: 
    blackword_sets: 
    twitter_ids: ['2214993781']
    webhook_urls: ['https://discord.com/api/webhooks/839673177201311785/6JdsiucU9yt9eq_l1acE4uAsRcdTE-SPdJJTP8U4OaQN7180UJiuNVqMB3r0sY6w6-xE']
#14
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    IncludeAttachment: false
    IncludeQuote: false
    CreateEmbed: false
    custom_message: '{user} tweeted: {url}'
    keyword_sets: [['t.co'],['http']]
    blackword_sets: 
    twitter_ids: ['1273568469099794432','1236284617776226306','1151291278971133953','1411545154217930754','923809384982913025','1195218720387321856','1222630584415129600','3064628602']
    webhook_urls: ['https://discord.com/api/webhooks/869806469632122900/XZG_BRjwizn-T1pzeDCkcKFMbHHXlj0j8j8whCgpewoVs7DgvP2ekP3An7gUOx8L7PoY']


# configuration through environment variables
  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER!b}
    IncludeRetweet: ${INCLUDE_RETWEET!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY!b}
    IncludeAttachment: ${INCLUDE_ATTACHMENT!b}
    IncludeQuote: ${INCLUDE_QUOTE!b}
    CreateEmbed: ${CREATE_EMBED!b}
    custom_message: ${CUSTOM_MESSAGE}
    keyword_sets: ${KEYWORDS!ll}
    blackword_sets: ${BLACKWORDS!ll}
    twitter_ids: ${TWITTER_ID!l}
    twitter_handles: ${TWITTER_HANDLE!l}
    twitter_lists: ${TWITTER_LIST!l}
    track: ${TRACK!l}
    location: ${LOCATION!fl}
    webhook_urls: ${WEBHOOK_URL!wh}

  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER_2!b}
    IncludeRetweet: ${INCLUDE_RETWEET_2!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY_2!b}
    IncludeAttachment: ${INCLUDE_ATTACHMENT_2!b}
    IncludeQuote: ${INCLUDE_QUOTE_2!b}
    CreateEmbed: ${CREATE_EMBED_2!b}
    custom_message: ${CUSTOM_MESSAGE_2}
    keyword_sets: ${KEYWORDS_2!ll}
    blackword_sets: ${BLACKWORDS_2!ll}
    twitter_ids: ${TWITTER_ID_2!l}
    twitter_handles: ${TWITTER_HANDLE_2!l}
    twitter_lists: ${TWITTER_LIST_2!l}
    track: ${TRACK_2!l}
    location: ${LOCATION_2!fl}
    webhook_urls: ${WEBHOOK_URL_2!wh}



  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER_10!b}
    IncludeRetweet: ${INCLUDE_RETWEET_10!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY_10!b}
    IncludeAttachment: ${INCLUDE_ATTACHMENT_10!b}
    IncludeQuote: ${INCLUDE_QUOTE_10!b}
    CreateEmbed: ${CREATE_EMBED_10!b}
    custom_message: ${CUSTOM_MESSAGE_10}
    keyword_sets: ${KEYWORDS_10!ll}
    blackword_sets: ${BLACKWORDS_10!ll}
    twitter_ids: ${TWITTER_ID_10!l}
    twitter_handles: ${TWITTER_HANDLE_10!l}
    twitter_lists: ${TWITTER_LIST_10!l}
    track: ${TRACK_10!l}
    location: ${LOCATION_10!fl}
    webhook_urls: ${WEBHOOK_URL_10!wh}
    
  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER_99!b}
    IncludeRetweet: ${INCLUDE_RETWEET_99!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY_99!b}
    IncludeAttachment: ${INCLUDE_ATTACHMENT_99!b}
    IncludeQuote: ${INCLUDE_QUOTE_99!b}
    CreateEmbed: ${CREATE_EMBED_99!b}
    custom_message: ${CUSTOM_MESSAGE_99}
    keyword_sets: ${KEYWORDS_99!ll}
    blackword_sets: ${BLACKWORDS_99!ll}
    twitter_ids: ${TWITTER_ID_99!l}
    twitter_handles: ${TWITTER_HANDLE_99!l}
    twitter_lists: ${TWITTER_LIST_99!l}
    track: ${TRACK_99!l}
    location: ${LOCATION_99!fl}
    webhook_urls: ${WEBHOOK_URL_99!wh}
